#!/usr/bin/env node

// vim: set filetype=javascript:

//  ---------------------------------------------------------------------------------------------------------------  //

var nopt = require( 'nopt' );

var teya = require( './lib/teya.js' );

//  ---------------------------------------------------------------------------------------------------------------  //

var options = get_options();

if ( options.help ) {
    help();

} else if ( options.version ) {
    version();

} else if ( options.data && options.template ) {
    var data = eval( '(' + options.data + ')' );

    var files = get_teya_files( options );
    for ( var i = 0, l = files.length; i < l; i++ ) {
        var filename = files[ i ];

        console.log( teya.run( filename, data, options.template ) );
    }

} else if ( options.ast ) {
    var files = get_teya_files( options );
    for ( var i = 0, l = files.length; i < l; i++ ) {
        var filename = files[ i ];

        var ast = teya.parse( filename );
        console.log( ast.to_string( true ) );
    }

} else {
    var files = get_teya_files( options );
    for ( var i = 0, l = files.length; i < l; i++ ) {
        var filename = files[ i ];

        teya.compile( filename );
    }
}

//  ---------------------------------------------------------------------------------------------------------------  //

function get_options() {
    var options = nopt(
        {
            'help': Boolean,
            'version': Boolean,
            'data': String,
            'template': String,
            'ast': Boolean,
        },
        {
            'h': '--help',
            'v': '--version',
            'd': '--data',
            't': '--template',
            'a': '--ast',
        }
    );

    return options;
}

function get_teya_files( options ) {
    var files = options.argv.remain;
    var teya_files = [];

    for ( var i = 0, l = files.length; i < l; i++ ) {
        var filename = files[ i ];
        if ( /\.teya$/.test( filename ) ) {
            teya_files.push( filename );
        }
    }

    if ( !teya_files.length ) {
        help();

        process.exit( 1 );
    }

    return teya_files;
}

//  ---------------------------------------------------------------------------------------------------------------  //

function help() {
    console.log( 'USAGE:');
    console.log( '' );
    console.log( '    teya --help' );
    console.log( '    teya --version' );
    console.log( '' );
    console.log( '    teya filename.teya' );
    console.log( '' );
};

function version() {
    console.log( require( './package.json' ).version );
}

//  ---------------------------------------------------------------------------------------------------------------  //

