#!/usr/bin/env node

// vim: set filetype=javascript:

//  ---------------------------------------------------------------------------------------------------------------  //

var fs_ = require( 'fs' );
var path_ = require( 'path' );

var _ = require( 'lodash' );
var nopt = require( 'nopt' );

var no = require( 'nommon' );
require( 'no.colors' );

var teya = require( '../lib/teya.js' );
var Terror = require( '../lib/terror.js' );

//  ---------------------------------------------------------------------------------------------------------------  //

var options = nopt(
    {
        'diff': String,
        'result': String
    },
    {
        'd': '--diff',
        'r': '--result',
    }
);

var mode;
if ( options.diff ) {
    mode = 'diff';
} else if ( options.result ) {
    mode = 'result';
} else {
    mode = 'compact';
}

//  ---------------------------------------------------------------------------------------------------------------  //

console.log( '' );

var files = get_files();

var oks = 0;
var fails = 0;

for (var i = 0, l = files.length; i < l; i++) {
    var filename = files[ i ];

    var content = fs_.readFileSync( filename, 'utf-8' );
    var tests = eval( '(' + content + ')' );
    if ( !Array.isArray( tests ) ) {
        tests = [ tests ];
    }

    var test_oks = 0;
    var test_fails = 0;
    var k = tests.length;

    var teya_filename = filename.replace( /\.test$/, '.teya' );

    var output = '';
    for ( var j = 0; j < k; j++ ) {
        var test = tests[ j ];

        var data = test.data;
        if ( typeof data === 'string' && /\.(data|json)$/.test( data ) ) {
            //  Резолвим имя файла с данными относительно имени файла с самим тестом.
            data = path_.join( path_.dirname( filename ), data );
        }
        var template = test.template || 'page';

        try {
            var result = teya.run( teya_filename, template, data );

            if ( _.isEqual( test.result, result ) ) {
                test_oks++;
                switch ( mode ) {
                    case 'compact':
                        output += '*'.green;
                        break;
                    case 'result':
                    case 'diff':
                        output += format_result( result ).green + '\n\n';
                        break;
                }

            } else {
                test_fails++;
                switch ( mode ) {
                    case 'compact':
                        output += '*'.red;
                        break;
                    case 'result':
                        output += format_result( result ).red + '\n\n';
                        break;
                    case 'diff':
                        output += format_result( test.result ).green + '\n' + format_result( result ).red + '\n\n';
                        break;
                }
            }

        } catch ( e ) {
            if ( test.error && ( e instanceof Terror ) && ( e.id === test.error.id ) && _.isEqual( test.error.params, e.params ) ) {
                test_oks++;
                switch ( mode ) {
                    case 'compact':
                        output += '*'.green;
                        break;
                    case 'result':
                    case 'diff':
                        output += 'throws'.green + '\n';
                        break;
                }

            } else {
                test_fails++;
                switch ( mode ) {
                    case 'compact':
                        output += '*'.red;
                        break;
                    case 'result':
                    case 'diff':
                        output += 'throws'.red + '\n';
                        break;
                }
            }
        }
    }

    switch ( mode ) {
        case 'compact':
            output = no.string.pad_left( filename, 30 ).gray + ' ' + output;
            break;
        case 'result':
        case 'diff':
            output = output.replace( /^/gm, no.string.repeat( ' ', 20 ) );
            output = no.string.pad_left( filename, 30 ).gray + '\n' + output;
    }

    console.log( output );

    oks += test_oks;
    fails += test_fails;
}

console.log();
console.log( 'ok: %s, fail: %s\n', oks.toString().green, fails.toString().red );

//  ---------------------------------------------------------------------------------------------------------------  //

function format_result( result ) {
    if ( typeof result !== 'string' ) {
        return JSON.stringify( result, null, 4 );
    }

    if ( !result ) {
        return '""';
    }

    return result;
}

//  ---------------------------------------------------------------------------------------------------------------  //

function get_files( dir, result ) {
    var argv = process.argv;
    if ( !result && ( argv.length > 1 ) ) {
        result = [];
        for ( var i = 2; i < argv.length; i++ ) {
            var arg = argv[ i ];
            if ( /\.test$/.test( arg ) ) {
                result.push( arg );
            }
        }

        if ( result.length ) {
            return result;
        }
    }

    result = result || [];

    dir = dir || '.';

    var items = fs_.readdirSync( dir ).sort();
    for ( var i = 0, l = items.length; i < l; i++ ) {
        var item = path_.join( dir, items[ i ] );

        var stat = fs_.statSync( item );
        if ( stat.isFile() && /\.test$/.test( item ) ) {
            result.push( item );
        } else if ( stat.isDirectory() ) {
            get_files( item, result );
        }
    }

    return result;
}

//  ---------------------------------------------------------------------------------------------------------------  //

